Applications/WebApp/Models/WalletInfo/TransactionResposneVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Applications.WebApp.Models.WalletInfo
{
    public class TransactionResposneVM
    {
        public decimal Inflow { get; set; }
        public decimal Outflow { get; set; }
        public string Type { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public decimal WalletBalance { get; set; }
        public DateTime TransactionDateTime { get; set; }
    }
}

Applications/WebApp/Models/WalletInfo/WalletInfoPageVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Applications.WebApp.Models.WalletInfo
{
    public class WalletInfoPageVM
    {
        public WalletInfoRequestVM WalletInfoRequestVM { get; set; }
        public WalletInfoResponseVM WalletInfoResponseVM { get; set; }
    }
}

Applications/WebApp/Models/WalletInfo/WalletInfoRequestVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Applications.WebApp.Models.WalletInfo
{
    public class WalletInfoRequestVM
    {
        public string Jmbg { get; set; }
        public string Password { get; set; }
    }
}

Applications/WebApp/Models/WalletInfo/WalletInfoResponseVM.cs
using Applications.WebApp.Models.WalletInfo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Applications.WebApp.Models.WalletInfo
{
    public class WalletInfoResponseVM
    {
        public string Jmbg { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BankAccount { get; set; }
        public string BankType { get; set; }
        public decimal Balance { get; set; }
        public decimal UsedDepositThisMonth { get; set; }
        public decimal MaximalDeposit { get; set; }
        public decimal UsedWithdrawThisMonth { get; set; }
        public decimal MaximalWithdraw { get; set; }
        public bool IsBlocked { get; set; }
        public List<TransactionResposneVM> TransactionVMs { get; set; }
    }
}

Applications/WebApp/Controllers/WalletController.cs
using Applications.WebApp.Models;
using Applications.WebApp.Models.WalletInfo;
using Common.Utils;
using Core.ApplicationServices;
using Core.ApplicationServices.DTOs;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Applications.WebApp.Controllers
{
    public class WalletController : Controller
    {
        private readonly WalletService WalletService;

        public WalletController(WalletService walletService)
        {
            WalletService = walletService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(WalletVM walletVM)
        {
            string password;
            try
            {
                password = await WalletService.CreateWallet(walletVM.FirstName, walletVM.LastName, walletVM.Jmbg, walletVM.BankType, walletVM.PIN, walletVM.BankAccount);
                ModelState.Clear();
                return View(new WalletVM() { Password = password });
            }
            catch(Exception ex)
            {
                ViewData["IsSuccessful"] = "no";
                ViewData["ErrorMessage"] = ex.Message;

                return View();
            }
        }

        [HttpGet]
        public IActionResult Deposit()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Deposit(WalletDepositVM walletDepositVM)
        {
            try
            {
                await WalletService.Deposit(walletDepositVM.Jmbg, walletDepositVM.Password, walletDepositVM.Amount);
                ModelState.Clear();
                ViewData["IsSuccessful"] = "yes";
                return View();
            }
            catch (Exception ex)
            {
                ViewData["IsSuccessful"] = "no";
                ViewData["ErrorMessage"] = ex.Message;

                return View();
            }
        }

        [HttpGet]
        public IActionResult Withdraw()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Withdraw(WalletWithdrawVM walletWithdrawVM)
        {
            try
            {
                await WalletService.Withdraw(walletWithdrawVM.Jmbg, walletWithdrawVM.Password, walletWithdrawVM.Amount);
                ModelState.Clear();
                ViewData["IsSuccessful"] = "yes";
                return View();
            }
            catch (Exception ex)
            {
                ViewData["IsSuccessful"] = "no";
                ViewData["ErrorMessage"] = ex.Message;

                return View();
            }
        }

        [HttpGet]
        public IActionResult Transfer()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Transfer(WalletTransferVM walletTransferVM)
        {
            try
            {
                await WalletService.Transfer(walletTransferVM.JmbgFrom , walletTransferVM.PasswordFrom, walletTransferVM.JmbgTo, walletTransferVM.Amount);
                ModelState.Clear();
                ViewData["IsSuccessful"] = "yes";
                return View();
            }
            catch (Exception ex)
            {
                ViewData["IsSuccessful"] = "no";
                ViewData["ErrorMessage"] = ex.Message;

                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> CalculateFee([FromBody] CalculateFeeVM calculateFeeVM)
        {
            try
            {
                decimal fee = await WalletService.CalculateTransferFee(calculateFeeVM.Jmbg, calculateFeeVM.Password, calculateFeeVM.Amount);
                return Ok(fee);
            }
            catch (Exception ex)
            {
                return BadRequest(new { errorMessage = ex.Message });
            }
        }

        [HttpGet]
        public IActionResult WalletInfo()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> WalletInfo(WalletInfoRequestVM walletInfoRequestVM)
        {
            try
            {
                WalletInfoDTO walletInfoDTO = await WalletService.GetWalletInfo(walletInfoRequestVM.Jmbg, walletInfoRequestVM.Password);
                WalletInfoResponseVM walletInfoResponseVM =
                    new WalletInfoResponseVM()
                    {
                        Jmbg = walletInfoDTO.Jmbg,
                        FirstName = walletInfoDTO.FirstName,
                        LastName = walletInfoDTO.LastName,
                        BankType = EnumMapper.MapBankType(walletInfoDTO.BankType),
                        BankAccount = walletInfoDTO.BankAccount,
                        Balance = walletInfoDTO.Balance,
                        UsedDepositThisMonth = walletInfoDTO.UsedDepositThisMonth,
                        MaximalDeposit = walletInfoDTO.MaximalDeposit,
                        UsedWithdrawThisMonth = walletInfoDTO.UsedWithdrawThisMonth,
                        MaximalWithdraw = walletInfoDTO.MaximalWithdraw,
                        IsBlocked = walletInfoDTO.IsBlocked,
                        TransactionVMs = walletInfoDTO.TransactionDTOs.Select(
                                transaction => new TransactionResposneVM() {
                                    Inflow = (EnumMapper.MapTransactionTypeFlow(transaction.Type) == "Inflow" ? transaction.Amount : 0M),
                                    Outflow = (EnumMapper.MapTransactionTypeFlow(transaction.Type) == "Outflow" ? transaction.Amount : 0M),
                                    Destination = transaction.Destination,
                                    Source = transaction.Source,
                                    TransactionDateTime = transaction.TransactionDateTime,
                                    Type = EnumMapper.MapTransactionType(transaction.Type),
                                    WalletBalance = transaction.WalletBalance
                                }
                            ).OrderByDescending(t => t.TransactionDateTime).ToList()
                    };
                ModelState.Clear();
                return View(new WalletInfoPageVM(){ WalletInfoResponseVM = walletInfoResponseVM });
            }
            catch (Exception ex)
            {
                ViewData["IsSuccessful"] = "no";
                ViewData["ErrorMessage"] = ex.Message;

                return View();
            }
        }

        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordVM changePasswordVM)
        {
            try
            {
                await WalletService.ChangePassword(changePasswordVM.Jmbg, changePasswordVM.OldPassword, changePasswordVM.NewPassword, changePasswordVM.NewPasswordConfirmation);
                ModelState.Clear();
                ViewData["IsSuccessful"] = "yes";
                return View();
            }
            catch (Exception ex)
            {
                ViewData["IsSuccessful"] = "no";
                ViewData["ErrorMessage"] = ex.Message;

                return View();
            }
        }


        [HttpGet]
        public IActionResult AdministerWallet()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AdministerWallet(WalletAdministrationVM walletAdministrationVM)
        {
            try
            {
                if (walletAdministrationVM.Action == "Block")
                {
                    await WalletService.BlockWallet(walletAdministrationVM.Jmbg, walletAdministrationVM.AdminPassword);
                    ModelState.Clear();
                    ViewData["SuccessMessage"] = "Wallet has been blocked successfully";
                }
                else if (walletAdministrationVM.Action == "Unblock")
                {
                    await WalletService.UnblockWallet(walletAdministrationVM.Jmbg, walletAdministrationVM.AdminPassword);
                    ModelState.Clear();
                    ViewData["SuccessMessage"] = "Wallet has been unblocked successfully";
                }
                else
                {
                    throw new ArgumentException("Unknown action");
                }
                ViewData["IsSuccessful"] = "yes";
                return View();
            }
            catch (Exception ex)
            {
                ViewData["IsSuccessful"] = "no";
                ViewData["ErrorMessage"] = ex.Message;

                return View();
            }
        }


    }
}

Applications/WebApp/Views/Wallet/AdministerWallet.cshtml
@model WalletAdministrationVM




<div class="container">
    <h1 style="margin-bottom:2vh;">Block/Unblock wallet</h1>


    <div class="row">
        <div class="col-md-6">
            <form asp-action="AdministerWallet" asp-controller="Wallet" method="post">
                <div class="form-group">
                    <label class="control-label" asp-for="Jmbg">Jmbg:</label>
                    <input class="form-control" asp-for="Jmbg" />
                    <span asp-validation-for="Jmbg" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="AdminPassword">Admin password:</label>
                    <input type="password" class="form-control" asp-for="AdminPassword" autocomplete="off" />
                    <span asp-validation-for="AdminPassword" class="text-danger"></span>
                </div>

                <div class="form-check">
                    <input class="form-check-input" type="radio" id="flexRadioDefault1" asp-for="Action" value="Block" checked>
                    <label class="form-check-label" for="flexRadioDefault1" asp-for="Action">
                        Block
                    </label>
                    <span asp-validation-for="Action" class="text-danger"></span>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" id="flexRadioDefault2" asp-for="Action" value="Unblock">
                    <label class="form-check-label" for="flexRadioDefault2" asp-for="Action">
                        Unblock
                    </label>
                    <span asp-validation-for="Action" class="text-danger"></span>
                </div>

                <input type="submit" value="Confirm" class="btn btn-primary mt-2" />
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="modalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalContent">
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/wallet.js"></script>
    @if (ViewData["IsSuccessful"] != null)
    {
        <script type="text/javascript">ShowMessage('@ViewData["IsSuccessful"].ToString()', '@(ViewData["SuccessMessage"] == null ? "" : ViewData["SuccessMessage"])', '@(ViewData["ErrorMessage"] == null ? "" : ViewData["ErrorMessage"])');</script>
    }
}

Applications/WebApp/Views/Wallet/ChangePassword.cshtml
@model ChangePasswordVM




<div class="container">
    <h1 style="margin-bottom:2vh;">Change passoword</h1>


    <div class="row">
        <div class="col-md-6">
            <form asp-action="ChangePassword" asp-controller="Wallet" method="post">
                <div class="form-group">
                    <label class="control-label" asp-for="Jmbg">Jmbg:</label>
                    <input class="form-control" asp-for="Jmbg" />
                    <span asp-validation-for="Jmbg" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="OldPassword">Old password:</label>
                    <input type="password" class="form-control" asp-for="OldPassword" autocomplete="off" />
                    <span asp-validation-for="OldPassword" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="NewPassword">New password:</label>
                    <input type="password" class="form-control" asp-for="NewPassword" autocomplete="off" />
                    <span asp-validation-for="NewPassword" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="NewPasswordConfirmation">Confirm new password:</label>
                    <input type="password" class="form-control" asp-for="NewPasswordConfirmation" autocomplete="off" />
                    <span asp-validation-for="NewPasswordConfirmation" class="text-danger"></span>
                </div>
                <input type="submit" value="Confirm" class="btn btn-primary" />
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="modalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalContent">
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/wallet.js"></script>
    @if (ViewData["IsSuccessful"] != null)
    {
        <script type="text/javascript">ShowMessage('@ViewData["IsSuccessful"].ToString()', 'Successfuly changed password', '@(ViewData["ErrorMessage"] == null ? "" : ViewData["ErrorMessage"])');</script>
    }
}

Applications/WebApp/Views/Wallet/Create.cshtml
@model WalletVM


<div class="container">
    <h1 style="margin-bottom:2vh;">New wallet</h1>
    @if (Model?.Password != null)
    {
        <h2 style="margin-bottom:3vh;"> Password: <input disabled="disabled" value="@Model.Password" class="col-md-2"></h2>
    }
    <div class="row">
        <div class="col-md-6">
            <form asp-action="Create" asp-controller="Wallet" method="post">
                <div class="form-group">
                    <label class="control-label" asp-for="FirstName">First name:</label>
                    <input class="form-control" asp-for="FirstName" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="LastName">Last name:</label>
                    <input class="form-control" asp-for="LastName" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="Jmbg">Jmbg:</label>
                    <input class="form-control" asp-for="Jmbg" />
                    <span asp-validation-for="Jmbg" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="BankAccount">Bank account:</label>
                    <input class="form-control" asp-for="BankAccount" />
                    <span asp-validation-for="BankAccount" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="PIN">PIN:</label>
                    <input type="password" class="form-control" asp-for="PIN" />
                    <span asp-validation-for="PIN" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="BankType" class="control-label">Bank:</label>
                    <select asp-for="BankType" class="form-control" asp-items="Html.GetEnumSelectList<BankType>().Where(type => type.Value != 0.ToString())">
                        <option selected>Please select</option>
                    </select>
                    <span asp-validation-for="BankType" class="text-danger"></span>
                </div>

                <input type="submit" value="Confirm" class="btn btn-primary" />
            </form>
        </div>
    </div>
</div>


<div class="modal fade" id="modalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalContent">
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/wallet.js"></script>
    @if (ViewData["IsSuccessful"] != null)
    {
        <script type="text/javascript">ShowMessage('@ViewData["IsSuccessful"].ToString()', '', '@(ViewData["ErrorMessage"] == null ? "" : ViewData["ErrorMessage"])');</script>
    }
}

Applications/WebApp/Views/Wallet/Deposit.cshtml
@model WalletDepositVM




<div class="container">
    <h1 style="margin-bottom:2vh;">Deposit</h1>


    <div class="row">
        <div class="col-md-6">
            <form asp-action="Deposit" asp-controller="Wallet" method="post">
                <div class="form-group">
                    <label class="control-label" asp-for="Jmbg">Jmbg:</label>
                    <input class="form-control" asp-for="Jmbg" />
                    <span asp-validation-for="Jmbg" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="Password">Password:</label>
                    <input type="password" class="form-control" asp-for="Password" autocomplete="off" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="Amount">Amount:</label>
                    <input id="Amount" class="form-control" pattern="^\d*(\.\d{0,2})?$" asp-format="{0:0.##}" asp-for="Amount" min="1" max="9999999999" autocomplete="off" />
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <input type="submit" value="Confirm" class="btn btn-primary" />
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="modalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalContent">
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/wallet.js"></script>
    @if (ViewData["IsSuccessful"] != null)
    {
        <script type="text/javascript">ShowMessage('@ViewData["IsSuccessful"].ToString()', 'Successfuly deposited funds', '@(ViewData["ErrorMessage"] == null ? "" : ViewData["ErrorMessage"])');</script>
    }
}

Applications/WebApp/Views/Wallet/Transfer.cshtml
@model WalletTransferVM




<div class="container">
    <h1 style="margin-bottom:2vh;">Transfer</h1>


    <div class="row">
        <div class="col-md-6">
            <form asp-action="Transfer" asp-controller="Wallet" method="post">
                <div class="form-group">
                    <label class="control-label" asp-for="JmbgFrom">Jmbg from:</label>
                    <input class="form-control" asp-for="JmbgFrom" onchange="CalculateFee()"/>
                    <span asp-validation-for="JmbgFrom" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="PasswordFrom">Password:</label>
                    <input type="password" class="form-control" asp-for="PasswordFrom" autocomplete="off" onchange="CalculateFee()"/>
                    <span asp-validation-for="PasswordFrom" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="JmbgTo">Jmbg to:</label>
                    <input class="form-control" asp-for="JmbgTo" />
                    <span asp-validation-for="JmbgTo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="Amount">Amount:</label>
                    <input id="TransferAmount" class="form-control" pattern="^\d*(\.\d{0,2})?$" asp-format="{0:0.##}" asp-for="Amount" min="1" max="9999999999" autocomplete="off" />
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="Fee">Fee:</label>
                    <input id="Fee" class="form-control" asp-format="{0:0.##}" asp-for="Fee" max="9999999999" autocomplete="off" disabled="disabled"/>
                    <span asp-validation-for="Fee" class="text-danger"></span>
                </div> 
                <input type="submit" value="Confirm" class="btn btn-primary" />
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="modalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalContent">
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/wallet.js"></script>
    @if (ViewData["IsSuccessful"] != null)
    {
        <script type="text/javascript">ShowMessage('@ViewData["IsSuccessful"].ToString()', 'Successfuly transfered funds','@(ViewData["ErrorMessage"] == null ? "" : ViewData["ErrorMessage"])');</script>
    }
}

Applications/WebApp/Views/Wallet/Withdraw.cshtml
@model WalletWithdrawVM




<div class="container">
    <h1 style="margin-bottom:2vh;">Withdraw</h1>
    <div class="row">
        <div class="col-md-6">
            <form asp-action="Withdraw" asp-controller="Wallet" method="post">
                <div class="form-group">
                    <label class="control-label" asp-for="Jmbg">Jmbg:</label>
                    <input class="form-control" asp-for="Jmbg" />
                    <span asp-validation-for="Jmbg" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="Password">Password:</label>
                    <input type="password" class="form-control" asp-for="Password" autocomplete="off" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label" asp-for="Amount">Amount:</label>
                    <input id="Amount" class="form-control" pattern="^\d*(\.\d{0,2})?$" asp-format="{0:0.##}" asp-for="Amount" min="1" max="9999999999" autocomplete="off" />
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <input type="submit" value="Confirm" class="btn btn-primary" />
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="modalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modalContent">
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/wallet.js"></script>
    @if (ViewData["IsSuccessful"] != null)
    {
        <script type="text/javascript">ShowMessage('@ViewData["IsSuccessful"].ToString()', 'Successfuly withdrew funds', '@(ViewData["ErrorMessage"] == null ? "" : ViewData["ErrorMessage"])');</script>
    }
}